### ISSUE TITLE
lmom_fit changes original data sorting it

### ISSUE THREAD

**Issue by rokopi-byte** [Ouranosinc/lmoments3#15]
Hi,
As reported [here](https://github.com/OpenHydrology/lmoments3/issues/2) long time ago.. calling lmom_fit changes the original data, sorting it ascending.
As a workaround I use `copy`:

`distr.gum.lmom_fit(H.copy())`

**Comment by aulemahal** [comment]
You are not going to like my answer : I was unable to reproduce the bug on my side, could you provide a "minimal working example" of the bug ?

For the record, I tested:
```python3
import lmoments3.distr as lm
a = [5, 23, 7, 33, 79, 4, 2]
lm.gum.lmom_fit(a)
```
And here, `a` is unchanged.

**Comment by rokopi-byte** [comment]
I noticed that the issue only occurs when the numpy array is of type float and only after sorting. There might be something wrong on my side with array copies and sorting, as I'm not that experienced in Python. Passing `H.copy()` solves the problem, but it shouldn't be necessary, should it?

```python
from lmoments3 import distr
import numpy as np

a = np.array([1.8, 2.5, 3.1, 4.9])
H = np.sort(a)[::-1]
print(H)
b = distr.wei.lmom_fit(H)
print(H)
```

This is produced:

```
[4.9 3.1 2.5 1.8]
[1.8 2.5 3.1 4.9]
```
